# Generated by Django 2.0.3 on 2018-03-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_airhostess_airport_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot',
            name='airport_name',
            field=models.CharField(default='kol', max_length=100),
            preserve_default=False,
        ),
    ]
