# Generated by Django 2.0.3 on 2018-03-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0003_pilot_airport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='date_and_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='traffic',
            name='date_and_time',
            field=models.DateField(),
        ),
    ]
